server:
  port: 80

spring:
  application:
    name: imusic

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE}?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USER_NAME}
    password: ${MySQL_PASSWORD}

  flyway:
    enabled: true

  jpa:
    generate-ddl: false
    show-sql: true


