MYSQL_ADDRESS: 10.38.106.215:3306
MYSQL_DATABASE: imusic
MYSQL_USER_NAME: root
MySQL_PASSWORD: 8PGCRqtc

WX_APP_ID: wx8b003496bd6f09fa
WX_APP_SECRET: 8ef209a98bd3f957d00f02ae3bb45c54
WX_TOKEN_KEY: 2HXLGC2YfMZhzoB0wlWkmTeE9zq